const {test}=require('node:test'),assert=require('node:assert/strict'),p=require('../location-policy');
const event={churrascoDate:'08/10/2026',hora:'12:00'},start=Date.parse('2026-10-08T15:00:00Z');
test('strict dates reject impossible calendar, format and hours',()=>{for(const [d,t] of [['31/02/2026','12:00'],['29/02/2025','12:00'],['08/10/2026','25:70'],['8/10/2026','12:00'],['08/13/2026','12:00'],['',''],[null,'12:00']])assert.equal(p.parseEventDateTime(d,t),null);assert.ok(p.parseEventDateTime('29/02/2024','12:00'));});
test('event instant uses Sao Paulo independently of host timezone',()=>assert.equal(+p.parseEventDateTime(event.churrascoDate,event.hora),start));
test('window opens inclusively and closes exclusively; malformed events fail closed',()=>{assert.equal(p.isOpen(event,start-p.HOUR-1),false);assert.equal(p.isOpen(event,start-p.HOUR),true);assert.equal(p.isOpen(event,start+4*p.HOUR),false);assert.equal(p.isOpen({},start),false);});
test('GPS updates retain original two hour deadline and never renew it',()=>{const s=p.session(event,'session',start);const next=p.position(s,'session',{latitude:1,longitude:2},start+p.HOUR);assert.equal(next.startedAt,start);assert.equal(next.expiresAt,start+2*p.HOUR);assert.equal(p.position(next,'session',{},start+2*p.HOUR),null);});
test('session duration is capped at event window closing',()=>assert.equal(p.session(event,'session',start+3*p.HOUR).expiresAt,start+4*p.HOUR));
test('missing, stopped or replaced sessions cannot be recreated by late GPS',()=>{assert.equal(p.position(null,'old',{},start),null);assert.equal(p.position(p.session(event,'new',start),'old',{},start),null);});
test('expiry strips coordinates and keeps deadline so update cannot restart',()=>{const old=p.position(p.session(event,'session',start),'session',{latitude:1,longitude:2},start);const cleaned=p.expiredWithoutCoordinates(old,start+2*p.HOUR);assert.equal('latitude' in cleaned,false);assert.equal('longitude' in cleaned,false);assert.equal(cleaned.expiresAt,old.expiresAt);assert.equal(p.position(cleaned,'session',{},start+3*p.HOUR),null);assert.equal(p.expiredWithoutCoordinates(old,start+p.HOUR),old);});
